[package]
name = "timetrackrs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"


[dependencies]
anyhow = "1.0.40"
byteorder = "1.4.3"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
hex = "0.4.3"
sysinfo = "0.17.0"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
rand = "0.8.3"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}

lazy_static = "1.4.0"

uuid = { version = "0.8.2", features = ["serde", "v4"] }
regex = "1.4.5"
battery = "0.7.8"
os_info = "3.0.2"
url = "2.2.1"
structopt = "0.3.21"
base64 = "0.13.0"
hmac = "0.10.1"
crypto-hashes = "0.9.0"
sha-1 = "0.9.4"
rust-crypto = "0.2.36"
rsa = "0.4.0"
openssl = "0.10.33"
tar = "0.4.33"
bzip2 = "0.4.2"
enum-utils = "0.1.2"
num_enum = "0.5.1"
enum_dispatch = "0.3.5"
zstd = "0.7.0"
tempfile = "3.2.0"
concat-reader = "0.1.0"
yup-oauth2 = "5.1.0"
hyper = "0.14.5"
hyper-rustls = "0.22.1"
hyper-tls = "0.5.0"
futures = "0.3.14"
csv = "1.1.6"
chrono-tz = "0.5.3"
log = "0.4.14"
pretty_env_logger = "0.4.0"
zip = "0.5.11"
youtube_dl = "0.6.1"
derive_more = "0.99.13"
directories-next = "2.0.0"
serde_regex = "1.1.0"
mediawiki = "0.2.7"
itertools = "0.10.0"
datachannel = { version = "0.5.0", features = ["static"], optional=true }
tokio = { version = "1.5.0", features = ["full"] }
tungstenite = "0.13.0"
futures-util = "0.3.14"
futures-channel = "0.3.14"
tokio-tungstenite = "0.14.0"
async-channel = "1.6.1"
whoami = "1.1.2"
multimap = "0.8.3"
paste = "1.0.5"
lru = { version = "0.6.5", features = ["nightly"] } # https://github.com/jeromefroe/lru-rs/pull/40
owning_ref = "0.4.1"
rust-embed = { version = "5.9.0", features = ["compression"] }
sqlx = { version = "0.5.1", features = ["sqlite", "any", "runtime-tokio-native-tls", "json"], git="https://github.com/phiresky/sqlx" }
warp = { version = "0.3.1", features = ["compression"] }
mime_guess = "2.0.3"
async-trait = "0.1.49"
ansi-escapes = "0.1.0"
tokio-stream = { version = "0.1.5", features = ["sync"] }
tokio-timer = "0.2.13"
addr = "0.14.0"
crc32fast = "1.2.1"
gethostname = "0.2.1"
md5 = "0.7.0"
wmi = "0.8.1"
user-idle = "0.4.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi","handleapi", "psapi"] }

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version = "0.8.1", features = ["screensaver"] }
xcb = "0.9.0"
nl80211 = {git="https://github.com/Eonm/nl80211", branch="master"}

[features]
sync = ["datachannel"]

[profile.dev.package."*"]
opt-level = 3

#[profile.release]
#lto="fat"


[[bin]]
name = "trbtt-sync"
required-features = ["sync"]

[[bin]]
name = "trbtt-signalling-server"
required-features = ["sync"]
