[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
default-run = "capture"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
anyhow = "1.0.26"
x11rb = "0.3.0"
byteorder = "1.3.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.44", features= ["preserve_order"] }
hex = "0.4.0"
sysinfo = "0.10.4"
chrono = { version = "0.4", features = ["serde"] }
diesel = {version = "1.4.3", features = ["sqlite"]}
dotenv = "0.15.0"
rand = "0.7.3"
diesel_migrations = "1.4.0"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
rocket = "0.4.2"
lazy_static = "1.4.0"
rocket_cors = "0.5.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
regex = "1.3.3"
battery = "0.7.5"
os_info = "1.3.1"
hostname = "0.3.0"
url = "2.1.1"

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["diesel_sqlite_pool"]
