[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
byteorder = "1.3.4"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = { version = "1.0.57", features = ["preserve_order"] }
hex = "0.4.2"
sysinfo = "0.15.1"
chrono = { version = "0.4.15", features = ["serde"] }
diesel = { version = "1.4.5", features = ["sqlite"] }
dotenv = "0.15.0"
rand = "0.7.3"
diesel_migrations = "1.4.0"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
rocket = "0.4.5"
lazy_static = "1.4.0"
rocket_cors = "0.5.2"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
regex = "1.3.9"
battery = "0.7.5"
os_info = "2.0.8"
hostname = "0.3.1"
url = "2.1.1"
structopt = "0.3.16"
base64 = "0.12.3"
hmac = "0.9.0"
crypto-hashes = "0.9.0"
sha-1 = "0.9.1"
rust-crypto = "0.2.36"
rsa = "0.3.0"
openssl = "0.10.30"
tar = "0.4.29"
flate2 = "1.0.16"
bzip2 = "0.4.1"
rusqlite = { version = "0.23.1", features = ["functions", "blob", "bundled"] }
enum-utils = "0.1.2"
num_enum = "0.5.1"
enum_dispatch = "0.3.2"
zstd = "0.5.3"
tempfile = "3.1.0"
concat-reader = "0.1.0"
google-fitness1 = "1.0.14"
yup-oauth2 = "4.1.2"
hyper = "0.13.7"
hyper-rustls = "0.21.0"
hyper-tls = "0.4.3"
futures = "0.3.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi","handleapi", "psapi"] }

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version = "0.6.0", features = ["screensaver"] }
xcb = "0.9.0"

[dependencies.rocket_contrib]
version = "0.4.5"
features = ["diesel_sqlite_pool"]

[profile.dev.package."*"]
opt-level = 3
