[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
anyhow = "1.0.26"
x11rb = "0.3.0"
byteorder = "1.3.2"
serde = "1.0.104"
serde_json = "1.0.44"
hex = "0.4.0"
sysinfo = "0.10.4"
chrono = "0.4.10"
