[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
byteorder = "1.3.4"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["preserve_order"] }
hex = "0.4.2"
sysinfo = "0.15.3"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.5", features = ["sqlite"] }
dotenv = "0.15.0"
rand = "0.7.3"
diesel_migrations = "1.4.0"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
rocket = "0.4.6"
lazy_static = "1.4.0"
rocket_cors = "0.5.2"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
regex = "1.4.2"
battery = "0.7.8"
os_info = "3.0.1"
hostname = "0.3.1"
url = "2.2.0"
structopt = "0.3.20"
base64 = "0.13.0"
hmac = "0.10.1"
crypto-hashes = "0.9.0"
sha-1 = "0.9.2"
rust-crypto = "0.2.36"
rsa = "0.3.0"
openssl = "0.10.30"
tar = "0.4.30"
bzip2 = "0.4.1"
rusqlite = { version = "0.23.1", features = ["functions", "blob", "bundled"] }
enum-utils = "0.1.2"
num_enum = "0.5.1"
enum_dispatch = "0.3.4"
zstd = "0.5.3"
tempfile = "3.1.0"
concat-reader = "0.1.0"
google-fitness1 = "1.0.14"
yup-oauth2 = "4.1.3"
hyper = "0.13.9"
hyper-rustls = "0.21.0"
hyper-tls = "0.4.3"
futures = "0.3.8"
publicsuffix = "1.5.4"
csv = "1.1.4"
chrono-tz = "0.5.3"
log = "0.4.11"
pretty_env_logger = "0.4.0"
zip = "0.5.8"
youtube_dl = "0.6.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi","handleapi", "psapi"] }

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version = "0.7.0", features = ["screensaver"] }
xcb = "0.9.0"

[dependencies.rocket_contrib]
version = "0.4.6"
features = ["diesel_sqlite_pool"]

[profile.dev.package."*"]
opt-level = 3
