[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
byteorder = "1.3.4"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = { version = "1.0.51", features = ["preserve_order"] }
hex = "0.4.2"
sysinfo = "0.13.3"
chrono = { version = "0.4.11", features = ["serde"] }
diesel = { version = "1.4.4", features = ["sqlite"] }
dotenv = "0.15.0"
rand = "0.7.3"
diesel_migrations = "1.4.0"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
rocket = "0.4.4"
lazy_static = "1.4.0"
rocket_cors = "0.5.2"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
regex = "1.3.6"
battery = "0.7.5"
os_info = "2.0.2"
hostname = "0.3.1"
url = "2.1.1"
structopt = "0.3.13"
base64 = "0.12.0"
hmac = "0.7.1"
crypto-hashes = "0.7.0"
sha-1 = "0.8.2"
rust-crypto = "0.2.36"
rsa = "0.2.0"
openssl = "0.10.29"
tar = "0.4.26"
flate2 = "1.0.14"
bzip2 = "0.3.3"
rusqlite = { version = "0.22.0", features = ["functions", "blob", "bundled"] }
enum-utils = "0.1.2"
num_enum = "0.4.3"
enum_dispatch = "0.3.0"
zstd = "0.5.1"
tempfile = "3.1.0"
concat-reader = "0.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winuser", "processthreadsapi","handleapi", "psapi"] }

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version="0.4.1", features=["screensaver"] }
xcb = "0.9.0"

[dependencies.rocket_contrib]
version = "0.4.4"
features = ["diesel_sqlite_pool"]

[profile.dev.package."*"]
opt-level = 3
