[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.38"
byteorder = "1.4.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
hex = "0.4.3"
sysinfo = "0.16.4"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
rand = "0.8.3"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
#rocket = { git = "https://github.com/SergioBenitez/Rocket" }
#rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", features=["diesel_sqlite_pool"] }
rocket = "*"
rocket_contrib = {version="*", features=["diesel_sqlite_pool"]}

lazy_static = "1.4.0"

uuid = { version = "0.8.2", features = ["serde", "v4"] }
regex = "1.4.4"
battery = "0.7.8"
os_info = "3.0.1"
hostname = "0.3.1"
url = "2.2.1"
structopt = "0.3.21"
base64 = "0.13.0"
hmac = "0.10.1"
crypto-hashes = "0.9.0"
sha-1 = "0.9.4"
rust-crypto = "0.2.36"
rsa = "0.3.0"
openssl = "0.10.32"
tar = "0.4.33"
bzip2 = "0.4.2"
rusqlite = { version = "0.24.2", features = ["functions", "blob", "bundled"] }
enum-utils = "0.1.2"
num_enum = "0.5.1"
enum_dispatch = "0.3.5"
zstd = "0.6.1"
tempfile = "3.2.0"
concat-reader = "0.1.0"
google-fitness1 = "1.0.14"
yup-oauth2 = "5.1.0"
hyper = "0.14.4"
hyper-rustls = "0.22.1"
hyper-tls = "0.5.0"
futures = "0.3.13"
publicsuffix = "1.5.6"
csv = "1.1.6"
chrono-tz = "0.5.3"
log = "0.4.14"
pretty_env_logger = "0.4.0"
zip = "0.5.11"
youtube_dl = "0.6.0"
derive_more = "0.99.11"
directories-next = "2.0.0"
serde_regex = "1.1.0"
mediawiki = "0.2.7"
itertools = "0.10.0"
datachannel = { version = "0.4.2", features = ["static"] }
tokio = { version = "1.3.0", features = ["full"] }
tungstenite = "0.13.0"
futures-util = "0.3.13"
futures-channel = "0.3.13"
tokio-tungstenite = "0.14.0"
async-channel = "1.6.1"
whoami = "1.1.0"
multimap = "0.8.2"
paste = "1.0.4"
lru = { version = "0.6.5", features = ["nightly"] } # https://github.com/jeromefroe/lru-rs/pull/40
owning_ref = "0.4.1"
libxid = "0.1.5"
rust-embed = "5.9.0"
sqlx = { version = "0.5.1", features = ["sqlite", "any", "runtime-tokio-native-tls", "json"] }
rocket_cors = "0.5.2"
warp = "0.3.0"

[patch.crates-io]
sqlx-macros = { path = "../sqlx/sqlx-macros" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi","handleapi", "psapi"] }

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version = "0.8.1", features = ["screensaver"] }
xcb = "0.9.0"
nl80211 = {git="https://github.com/Eonm/nl80211", branch="master"}


[profile.dev.package."*"]
opt-level = 3

#[profile.release]
#lto="fat"