[package]
name = "track-pc-usage-rs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
anyhow = "1.0.26"
x11rb = "0.3.0"
byteorder = "1.3.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.44", features= ["preserve_order"] }
hex = "0.4.0"
sysinfo = "0.10.4"
chrono = { version = "0.4", features = ["serde"] }
diesel = {version = "1.4.3", features = ["sqlite"]}
dotenv = "0.15.0"
rand = "0.7.3"
diesel_migrations = "1.4.0"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}
rocket = "0.4.2"
lazy_static = "1.4.0"
rocket_cors = "0.5.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
regex = "1.3.3"
battery = "0.7.5"
os_info = "1.3.1"
hostname = "0.3.0"
url = "2.1.1"
structopt = "0.3.7"
base64 = "0.11.0"
hmac = "0.7.1"
crypto-hashes = "0.7.0"
sha-1 = "0.8.2"
rust-crypto = "0.2.36"
rsa = "0.2.0"
openssl = "0.10.26"
tar = "0.4.26"
flate2 = "1.0.13"
bzip2 = "0.3.3"
rusqlite = {version ="0.20.0", features = ["functions", "blob"]}
enum-utils = "0.1.2"
num_enum = "0.4.2"
enum_dispatch = "0.2.0"
zstd = "0.5.1"
tempfile = "3.1.0"
concat-reader = "0.1.0"

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["diesel_sqlite_pool"]
